### ISSUE TITLE
yo angular generator version produces an output with one issue related to bower

### ISSUE THREAD

**Issue by sebasjimenez10** [addyosmani/yeoman-examples#15]
When using generator-angular@0.9.2 it produces an error described in this stackoverflow post: http://stackoverflow.com/questions/25784986/yeoman-grunt-no-such-file-or-directory-bower-json. In which finally the issue is fixed by commenting out a line of code as shown below:

```javascript
// Automatically inject Bower components into the app
wiredep: {
  options: {
    //cwd: '<%= yeoman.app %>'
  }
```

As I understood, this happens because the generator used (0.9.2) generates this issue. As a suggestion I would say to update the tutorial on the page and use a newer version of generator-angular (0.11.1)

**Comment by addyosmani** [comment]
Agreed. We have an upstream issue on the yeoman.io tracker to update the tutorial accordingly.

**Comment by sebasjimenez10** [comment]
Hey @addyosmani it's been a while since I posted this issue... do you think it can be marked as Solved?

**Comment by sebasjimenez10** [comment]
I'm going to close this since I believe it's solved in later versions.
